### ISSUE TITLE
direct children of a cayo component are not being rendered.

### ISSUE THREAD

**Issue by mgluf** [matthew-ia/cayo#135] opened 2023-09-05 21:01 UTC
```svelte
<!-- index.svelte -->
<Cayo src="foo.cayo.svelte">
  <div class="some">content</div>
</Cayo>


<!-- foo.cayo.svelte -->
<slot/>
```

The `.some` content will not render. This applies to named slots as well.

**Comment by mgluf** [comment] 2023-09-05 21:09
https://github.com/pm-destech/pm-f23-hp-banner-wayfare-pant/commit/e7933ade5cf8335f2b83d5ec83a99469d1d8ef5d

**Comment by matthew-ia** [comment] 2023-09-05 23:24
Related: https://github.com/matthew-ia/cayo/issues/9#issuecomment-951029538

**Comment by matthew-ia** [comment] 2023-09-06 00:32
I have found that this is by design, at least currently (and sort of by accident). 

First of all, `<Cayo>` is it's own component, not the component you are cayo-ifying. So, when you use it, it doesn't know about the named slots of *your* Cayo component. The default slot does actually work on the `<Cayo>` component, but there's more...

When a Cayo is hydrated, the entry point element's innerHTML of the component is replaced by the component's content. Remember, a `<Cayo>` basically just renders a Svelte App entry point for it to latch onto when it starting rendering. 

For example, 

```svelte
<!-- Usage -->
<Cayo src="some.cayo.svelte">
  Render me
</>

<!-- Output -->
<div data-cayo-id="some_r5unbn-1fo4wsh">
  <script data-cayo-props="" type="application/json">
    {}
  </script>
  Render me
</div>
```

> **Note**
> You can see this for yourself if you use you try to render a `<Cayo>`, but comment out the `renderCayos()` in your entry file (this will make it so the initial render shows, and it never hydrates the component.

But, as soon as the component get's hydrated, the div's innerHTML is replaced:
```html
<div data-cayo-id="some_r5unbn-1fo4wsh">
  <!-- component's rendered content here -->
</div>
```

This is actually part of the Svelte Client-side Component API, which we use to run components at runtime: 
> Whereas children of `target` are normally left alone, `hydrate: true` will cause any children to be removed.

We intentionally use `hydrate: true` in order to prevent the placeholder (default child of a component) being rendered in addition to the actual component content, otherwise you'd have this:

```html
<div data-cayo-id="some_r5unbn-1fo4wsh">
  Render me
  <!-- component's rendered content here -->
</div>
```

Now, how do we solve the issue — what if I want/need slots? Not sure yet...

Something pretty meta that might actually work: nest your `.cayo.svelte` component inside of a the `<Cayo>` as the child (default slot).

```svelte
import Some from '$lib/components/some.cayo.svelte';
<Cayo src="some.cayo.svelte">
  <Some>
    <!-- the slot content -->
  </Some>
</Cayo>
```

Note: tested that this works for the initial render as we'd expect, but then it still gets replaced during hydration.

I think in general slots are just not a thing for the root level of a Svelte app (which a Cayo component is).

**Comment by matthew-ia** [comment] 2024-03-25 13:45
Closing this since this isn't a common use case: use slots at the root of the Cayo Component instance. `<Cayo>` and `<Some>`(.cayo.svelte) are two different components, so the slots of `<Some>` don't apply to `<Cayo>`

**Closed** 2024-03-25 13:45 UTC
Labels: bug
